language: ruby
bundler_args: --without guard metrics
script: "bundle exec ruby spec/suite.rb"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode # JRuby in 1.8 mode
  # - jruby-19mode # JRuby in 1.9 mode Disabled for core dump http://travis-ci.org/#!/mbj/aequitas/jobs/1810636
  - rbx-18mode
  - rbx-19mode
notifications:
  email:
    - mbj@seonic.net
